ec2_constants:
  memory:
    m1_medium: 3840
    m1_large: 7680
    m2_2xlarge: 35020
  disk:
    m1_medium: 390000
    m1_large: 400000
    m2_2xlarge: 800000

name: (( merge ))
director_uuid: (( merge ))

releases: (( merge ))

compilation:
  workers: 6
  network: cf1
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: c1.medium
    availability_zone: (( properties.template_only.aws.availability_zone ))

update:
  canaries: 1
  canary_watch_time: 30000-600000
  update_watch_time: 30000-600000
  max_in_flight: 1
  max_errors: 1

networks:
  cf1:
    type: manual
    subnets:
      - range: 10.10.16.0/20
        name: default_unused
        reserved:
          - 10.10.16.2 - 10.10.16.9
          - 10.10.16.255 - 10.10.16.255
        static:
          - 10.10.16.10 - 10.10.16.254
        gateway: 10.10.16.1
        dns:
          - 10.10.0.2
        cloud_properties:
          security_groups:
            - cf
          subnet: (( properties.template_only.aws.subnet_ids.cf1 ))

resource_pools:
  small:
    network: cf1
    size: (( auto ))
    stemcell:
      name: bosh-stemcell
      version: latest
    cloud_properties:
      instance_type: m1.small
      availability_zone: (( properties.template_only.aws.availability_zone ))
  medium:
    network: cf1
    size: (( auto ))
    stemcell:
      name: bosh-stemcell
      version: latest
    cloud_properties:
      instance_type: m1.medium
      availability_zone: (( properties.template_only.aws.availability_zone ))
  large:
    network: cf1
    size: (( auto ))
    stemcell:
      name: bosh-stemcell
      version: latest
    cloud_properties:
      instance_type: m1.medium
      availability_zone: (( properties.template_only.aws.availability_zone ))
  dea:
    network: cf1
    size: (( auto ))
    stemcell:
      name: bosh-stemcell
      version: latest
    cloud_properties:
      instance_type: (( merge || "m1.large" ))
      availability_zone: (( properties.template_only.aws.availability_zone ))
  router:
    network: cf1
    size: (( auto ))
    stemcell:
      name: bosh-stemcell
      version: latest
    cloud_properties:
      instance_type: m1.small
      availability_zone: (( properties.template_only.aws.availability_zone ))
      elbs: (( merge || ["cfrouter"] ))

jobs:
  - name: syslog_aggregator
    template: syslog_aggregator
    instances: 1
    resource_pool: medium
    persistent_disk: (( merge || 100000 ))

    networks:
      - name: cf1
        static_ips: (( static_ips(jobs.syslog_aggregator.instances, "cf1.static") ))

  - name: nats
    template: nats
    instances: 1
    resource_pool: medium
    networks:
      - name: cf1
        static_ips: (( static_ips(jobs.nats.instances, "cf1.static") ))

  - name: uaa
    template: uaa
    instances: (( merge || 1 ))
    resource_pool: large
    networks:
      - name: cf1
        static_ips: (( static_ips(jobs.uaa.instances, "cf1.static") ))

  - name: login
    template: login
    instances: (( merge || 1 ))
    resource_pool: medium
    networks:
      - name: cf1

  - name: cloud_controller
    template: cloud_controller_ng
    instances: (( merge || 1 ))
    resource_pool: large
    networks:
      - name: cf1
        static_ips: (( static_ips(jobs.cloud_controller.instances, "cf1.static") ))
    properties:
      ccdb: ccdb

  - name: health_manager
    template: health_manager_next
    instances: 1
    resource_pool: medium
    networks:
      - name: cf1

  - name: dea_next
    template: (( merge || ["dea_next", "dea_logging_agent"] ))
    instances: (( merge || 1 ))
    update:
      max_in_flight: (( merge || 1 ))
    resource_pool: dea
    networks:
      - name: cf1
        default:
          - dns
          - gateway
    properties:
      dea_next:
        stacks:
          - lucid64

  - name: collector
    template: collector
    instances: 1
    resource_pool: small
    networks:
      - name: cf1

  - name: loggregator
    template: loggregator
    instances: (( merge || 1 ))
    resource_pool: small
    networks:
      - name: cf1
        static_ips: (( static_ips(jobs.loggregator.instances, "cf1.static") ))

  - name: router
    template: gorouter
    instances: (( merge || 1 ))
    resource_pool: router
    networks:
      - name: cf1
        default:
          - dns
          - gateway
        static_ips: (( static_ips(jobs.router.instances, "cf1.static") ))

properties:
  template_only: (( merge ))
  domain: (( merge ))
  system_domain: (( merge || domain ))
  system_domain_organization: (( merge || "" ))
  app_domains: (( merge || [domain] ))

  networks:
    apps: cf1
    management: cf1

  nats:
    user: (( merge ))
    password: (( merge ))
    address: 10.10.16.11
    port: 4222
    authorization_timeout: 5

  ccdb: (( merge ))

  uaadb:
    db_scheme: mysql
    address: (( merge ))
    port: 3306
    roles: (( merge ))
    databases: (( merge ))

  cc_api_version: v2

  cc:
    srv_api_uri: (( merge || "https://api." domain ))
    external_host: ccng
    logging_level: debug
    bulk_api_password: (( merge ))
    uaa_resource_id: cloud_controller
    staging_upload_user: (( merge ))
    staging_upload_password: (( merge ))
    max_staging_runtime: 900
    resource_pool:
      minimum_size: 65536
      resource_directory_key: (( merge || domain "-cc-resources" ))
      fog_connection:
        provider: AWS
        aws_access_key_id: (( properties.template_only.aws.access_key_id ))
        aws_secret_access_key: (( properties.template_only.aws.secret_access_key ))
      cdn:
        uri: (( merge || "" ))
        key_pair_id: (( merge || "" ))
        private_key: (( merge || "" ))
    packages:
      minimum_size: 1048576
      app_package_directory_key: (( merge || domain "-cc-packages" ))
      fog_connection:
        provider: AWS
        aws_access_key_id: (( properties.template_only.aws.access_key_id ))
        aws_secret_access_key: (( properties.template_only.aws.secret_access_key ))
      cdn:
        uri: (( merge || "" ))
        key_pair_id: (( merge || "" ))
        private_key: (( merge || "" ))
    droplets:
      minimum_size: 1048576
      droplet_directory_key: (( merge || domain "-cc-droplets" ))
      fog_connection:
        provider: AWS
        aws_access_key_id: (( properties.template_only.aws.access_key_id ))
        aws_secret_access_key: (( properties.template_only.aws.secret_access_key ))
      cdn:
        uri: (( merge || "" ))
        key_pair_id: (( merge || "" ))
        private_key: (( merge || "" ))
    cc_partition: default
    quota_definitions:
      free:
        memory_limit: 0
        total_services: 0
      paid:
        memory_limit: 10240
        total_services: -1
      runaway:
        memory_limit: 102400
        total_services: -1
    stacks:
      - name: lucid64
        description: "Ubuntu 10.04"
      - name: lucid64custom
        description: "Fake Ubuntu 10.04"
    db_encryption_key: (( merge ))
    tasks_disabled: (( merge || false ))

  router:
    port: 8081
    status:
      port: 8080
      user: (( merge ))
      password: (( merge ))

  dea:
    max_memory: 4096

  dea_next:
    memory_mb: (( merge || ec2_constants.memory.m2_2xlarge - 2048 ))
    memory_overcommit_factor: (( merge || 3 ))
    disk_mb: (( merge || ec2_constants.disk.m2_2xlarge - 2048 ))
    disk_overcommit_factor: (( merge || 1 ))
    num_instances: 256
    deny_networks:
      - 169.254.0.0/16
      - 10.10.0.0/24
      - 10.10.16.0/20
    allow_networks:
      - 10.10.0.2/32
      - 10.10.17.0/24

  syslog_aggregator:
    address: 10.10.16.10
    port: 54321
    relay_host: (( merge || "" ))
    relay_host_port: (( merge || 0 ))
    log_email:
      enabled: true
      from_email: (( merge || "" ))
      from_password: (( merge || "" ))
      to_email:
        - cfpi-backend@googlegroups.com
        - cfpi-services@googlegroups.com
      smtp_server: smtp.gmail.com
      smtp_port: 587
      smtp_domain: gmail.com

  loggregator:
    status:
      user: (( merge || "" ))
      password: (( merge || "" ))
      port: 5768

  login:
    protocol: https
    links:
      home: (( merge || "https://console." domain ))
      passwd: (( merge || "https://console." domain "/password_resets/new" ))
      signup: (( merge || "https://console." domain "/register" ))

  uaa:
    catalina_opts: -Xmx768m -XX:MaxPermSize=256m
    url: (( "https://uaa." domain ))
    resource_id: account_manager
    no_ssl: false
    jwt:
      signing_key: (( merge ))
      verification_key: (( merge ))
    cc:
      client_secret: (( merge ))
    admin:
      client_secret: (( merge ))
    batch:
      username: (( merge ))
      password: (( merge ))
    client:
      autoapprove:
        - cf
        - vmc
        - my
        - portal
        - micro
        - support-signon
        - login
    clients:
      login:
        override: true
        scope: openid
        authorities: oauth.login
        secret: (( merge ))
        authorized-grant-types: authorization_code,client_credentials,refresh_token
        redirect-uri: (( "https://login." domain ))
      portal:
        override: true
        scope: openid,cloud_controller.read,cloud_controller.write,password.write
        authorities: scim.write,scim.read,cloud_controller.read,cloud_controller.write,password.write,uaa.admin,uaa.resource,cloud_controller.admin,billing.admin
        secret: (( merge ))
        authorized-grant-types: authorization_code,client_credentials
        access-token-validity: 1209600
        refresh-token-validity: 1209600
      billing:
        override: true
        scope: uaa.none
        authorities: cloud_controller.read,cloud_controller.write,cloud_controller.admin,uaa.resource,scim.read,scim.write
        secret: (( merge ))
        authorized-grant-types: client_credentials
        access-token-validity: 1209600
        refresh-token-validity: 1209600
      app-direct:
        override: true
        authorities: app_direct_invoice.write
        secret: (( merge ))
        authorized-grant-types: authorization_code,client_credentials,password,refresh_token,implicit
        access-token-validity: 1209600
        refresh-token-validity: 1209600
        redirect-uri: (( login.links.home ))
      support-services:
        scope: scim.write,scim.read,openid,cloud_controller.read,cloud_controller.write
        secret: (( merge ))
        authorized-grant-types: authorization_code,client_credentials
        redirect-uri: (( "http://support-signon." domain ))
        authorities: portal.users.read
        access-token-validity: 1209600
        refresh-token-validity: 1209600
      vmc:
        override: true
        authorized-grant-types: password,implicit
        authorities: uaa.none
        scope: cloud_controller.read,cloud_controller.write,openid,password.write,cloud_controller.admin,scim.read,scim.write
      cf:
        override: true
        authorized-grant-types: implicit,password,refresh_token
        authorities: uaa.none
        scope: cloud_controller.read,cloud_controller.write,openid,password.write,cloud_controller.admin,scim.read,scim.write
      servicesmgmt:
        secret: (( merge ))
        scope: openid,cloud_controller.read,cloud_controller.write
        authorities: uaa.resource,oauth.service,clients.read,clients.write,clients.secret
        authorized-grant-types: authorization_code,client_credentials,password,implicit
        redirect-uri: (( "http://servicesmgmt." domain "/auth/cloudfoundry/callback" ))
        override: true
        autoapprove: true
      space-mail:
        override: true
        authorities: scim.read,scim.write,cloud_controller.admin
        secret: (( merge ))
        authorized-grant-types: client_credentials
        access-token-validity: 1209600
        refresh-token-validity: 1209600

    scim:
      users: (( merge ))

  collector:
    use_datadog: true
    datadog_api_key: (( properties.template_only.datadog.datadog_api_key ))
    datadog_application_key: (( properties.template_only.datadog.datadog_application_key ))
    deployment_name: (( name ))
